#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

PROGRAM_ROOT=$(dirname "${BASH_SOURCE[0]}")

if ! command -v go >/dev/null; then
  echo "Go not found on the system" >&2
  exit 1
fi

(cd "${PROGRAM_ROOT}" && go build -o gh-cherry-pick.out ./cmd/cherry-pick)
exec "${PROGRAM_ROOT}/gh-cherry-pick.out" "$@"
